---
name: Build and deploy with Docker Compose

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy in (GitHub Actions self-hosted runner tag)'
        required: true
        type: string
      image_name:
        description: 'Full image name to deploy'
        required: true
        type: string
      create_network_name:
        description: 'Create a network with the given name (to network different Compose projects)'
        required: false
        type: string
      prune_old_images:
        description: Prune old images
        type: boolean
        default: true
    secrets:
      cr_pat:
        description: 'GitHub Container Registry PAT'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}  # FIXME: We do this to get the newest commit after "Update version", but this is racy

      - id: get-version
        name: Get version from lerna.json
        run: |
          VERSION=$(node -p -e "require('./lerna.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: USERNAME
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: '${{inputs.image_name}}:${{ env.VERSION }}'
          push: true
          file: deployment/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deployment:
    needs: build
    runs-on: [self-hosted, '${{inputs.environment}}']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}  # FIXME: We do this to get the newest commit after "Update version", but this is racy

      # FIXME: Don't use the action in the master branch, but rather in the same ref. Doesn't seem to be possible:
      # https://web.archive.org/web/20220711004255/https://github.community/t/ref-head-in-reusable-workflows/203690
      - uses: uxland/actions/.github/actions/deploy-with-docker-compose@master
        with:
          image_name: '${{inputs.image_name}}'
          version: '${{needs.build.outputs.version}}'
          create_network_name: '${{inputs.create_network_name}}'
          cr_pat: '${{secrets.cr_pat}}'

      - name: Delete old Docker images
        if: ${{ inputs.prune_old_images == true }}
        run: docker image prune -a --filter "until=1000h" --force
