---
name: Notify deployment on Discord

on:
  workflow_call:
    inputs:
      event_name:
        description: 'Kind of event to notify (e.g. Deployment, Push, etc.)'
        required: false
        default: 'Deployment'
        type: string
      environment_name:
        description: 'Name of the environment for which to notify the event'
        required: false
        default: ${{ github.ref_name }}
        type: string
      is_success:
        description: 'Whether to notify success or failure'
        required: true
        type: boolean
    secrets:
      discord_webhook:
        description: 'Discord WebHook full URL'
        required: true

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify success
        uses: Ilshidur/action-discord@0.3.2
        if: ${{ inputs.is_success == true }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.discord_webhook }}
          EVENT_NAME: ${{ inputs.event_name }}
          ENVIRONMENT_NAME: ${{ inputs.environment_name }}
        with:
          args: '✅ {{ EVENT_NAME }} of {{ EVENT_PAYLOAD.repository.full_name }} to {{ ENVIRONMENT_NAME }} successful'

      - name: Notify failure
        uses: Ilshidur/action-discord@0.3.2
        if: ${{ inputs.is_success == false }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.discord_webhook }}
          EVENT_NAME: ${{ inputs.event_name }}
          ENVIRONMENT_NAME: ${{ inputs.environment_name }}
        with:
          args: '❌ {{ EVENT_NAME }} of {{ EVENT_PAYLOAD.repository.full_name }} to {{ ENVIRONMENT_NAME }} failed'
